
POST http://localhost:3003/api/v1/blogs/
Content-Type: application/json

{
    "id":4,
    "title":"Ijoriya",
    "content":"A beautiful novel",
    "author":"Subin Bhattarai",
    "likes":1500
}

###
PUT http://localhost:3003/api/v1/blogs/2
Content-Type: application/json

{
    "title":"Prison Break",
    "likes":50
}

###
GET http://localhost:3003/api/v1/blogs/

###
GET http://localhost:3003/api/v1/blogs/2

###
DELETE http://localhost:3003/api/v1/blogs/1
