
POST http://localhost:3003/api/v1/blogs/
Content-Type: application/json

{
    "id":8,
    "title":"",
    "content":"A story of a mayor in Kathmandu",
    "author":"Balen Shah",
    "likes":100
}

###
PUT http://localhost:3003/api/v1/blogs/3
Content-Type: application/json

{
    "author":""
}

###
GET http://localhost:3003/api/v1/blogs/

###
GET http://localhost:3003/api/v1/blogs/5

###
DELETE http://localhost:3003/api/v1/blogs/6
